[project]
name = "data-load"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
    "sqlalchemy>=2.0.46",
    "psycopg2-binary>=2.9.11",
]
